# Generated by Django 5.2.5 on 2025-08-26 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=50)),
                ('unique_id', models.CharField(max_length=20, unique=True)),
                ('publish_year', models.IntegerField()),
                ('copies_available', models.IntegerField(default=1)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
    ]
